import React from "react";
import {
  Workflow,
  BrainCircuit,
  Sparkles,
  ChartColumnIncreasing,
  MessageSquare,
  PanelsTopLeft,
  TrendingUpDown,
  ArrowBigDownDash,
  TrendingUp,
  FolderTree,
  Database,
  DatabaseZap,
  Layers3,
  ShieldAlert,
  UsersRound,
  LayoutGrid,
  Heart,
  Rocket,
  PieChart,
  Monitor,
  ClipboardCheck,
  Activity,
  HelpCircle,
  type LucideIcon,
  Server,
  Maximize2,
  ServerCrash,
  CircleGauge,
  Radar,
  Bug,
  ClockFading,
  FolderOpen,
  Network,
  LucideShieldCheck,
  FileCheck,
  Globe,
  Smartphone,
  SquareCode,
  Cloud,
  Landmark,
  MonitorCog,
  Search,
  MonitorSmartphone,
  Grid2X2Plus,
  PenTool,
  Compass,
  LayoutDashboard,
  ChartLine,
  CloudUpload,
  ServerCog,
  Shield,
  Waypoints,
  Radio,
  TriangleAlert,
  Wrench,
  Headset,
  ClipboardList,
  Bot,
  Cog,
  LocateFixed,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  workflow: Workflow,
  brainCircuit: BrainCircuit,
  globe: Globe,
  smartPhone: Smartphone,
  squareCode: SquareCode,
  cloud: Cloud,
  landMark: Landmark,
  monitorCog: MonitorCog,
  search: Search,
  monitorSmartphone: MonitorSmartphone,
  grid2X2Plus: Grid2X2Plus,
  penTool: PenTool,
  compass: Compass,
  layoutDashboard: LayoutDashboard,
  chartLine: ChartLine,
  cloudUpload: CloudUpload,
  serverCog: ServerCog,
  sparkles: Sparkles,
  shield: Shield,
  chartColumnIncreasing: ChartColumnIncreasing,
  messageSquare: MessageSquare,
  layout: PanelsTopLeft,
  trendingUPDown: TrendingUpDown,
  arrowDown: ArrowBigDownDash,
  trending: TrendingUp,
  folder: FolderTree,
  database: Database,
  databaseZap: DatabaseZap,
  layers: Layers3,
  brain: BrainCircuit,
  shieldAlert: ShieldAlert,
  waypoints: Waypoints,
  radio: Radio,
  triangleAlert: TriangleAlert,
  usersRound: UsersRound,
  layoutGrid: LayoutGrid,
  heart: Heart,
  rocket: Rocket,
  pieChart: PieChart,
  monitor: Monitor,
  clipboardCheck: ClipboardCheck,
  cog: Cog,
  activity: Activity,
  server: Server,
  maximize2: Maximize2,
  serverCrash: ServerCrash,
  circleGauge: CircleGauge,
  wrench: Wrench,
  headSet: Headset,
  clipboardList: ClipboardList,
  bot: Bot,
  locateFixed: LocateFixed,
  radar: Radar,
  bug: Bug,
  clockFading: ClockFading,
  network: Network,
  folderOpen: FolderOpen,
  shieldCheck: LucideShieldCheck,
  fileCheck: FileCheck,
};

interface ChallengesIconProps {
  icon: string;
  className?: string;
}

export default function ChallengesIcon({ icon, className }: ChallengesIconProps) {
  const IconComponent = iconMap[icon] || HelpCircle;
  return <IconComponent className={className} />;
}
